# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[test]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports

  publish:
    docker:
      - image: circleci/python:3.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: verify git tag vs. version
          command: python setup.py verify
      - run:
          name: create packages
          command: python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            set -o nounset
            pip install --user twine
            PATH=/home/circleci/.local/bin:$PATH
            twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - master
